# Generated by Django 4.2.1 on 2023-06-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='vacancy_id',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='vacancy_id',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='JobVacancy',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
